/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: aaflak6443 (https://sketchfab.com/aaflak6443)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mini-cooper-s-f9e222b6a78d413398434140212443ea
title: Mini Cooper S
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/MiniCooper.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object052_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object051_1.geometry} material={materials.Glass_front_lights} />
          </group>
          <group position={[0.62, 0.83, 0.85]}>
            <mesh geometry={nodes.Plane026_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0]}>
            <mesh geometry={nodes.Object011_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Plane021_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-0.25, 1, 0.85]}>
            <mesh geometry={nodes.Plane023_1.geometry} material={materials.Kuzov_potolok} />
          </group>
          <group position={[-0.21, 0.87, 0.82]}>
            <mesh geometry={nodes.Plane022_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-0.59, 0.78, 0.83]}>
            <mesh geometry={nodes.Object032_1.geometry} material={materials.Glass_backlights_white__1} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object038_1.geometry} material={materials.Glass_backlights} />
          </group>
          <group position={[0.27, 0.22, 0]}>
            <mesh geometry={nodes.Plane005_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[0, 0.76, 0.61]}>
            <mesh geometry={nodes.Object049_1.geometry} material={materials.Front_lights_Spec} />
          </group>
          <group position={[0, 0.76, 0.67]}>
            <mesh geometry={nodes.Line002_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[0, 0.76, 0.61]}>
            <mesh geometry={nodes.Line004_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[0, 0.76, 0.61]}>
            <mesh geometry={nodes.Object048_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object004_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[0, 0.76, 0.67]}>
            <mesh geometry={nodes.Object045_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[-0.08, 0.99, 0.86]}>
            <mesh geometry={nodes.Plane024_1.geometry} material={materials.Mirrors_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object019_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[-0.37, 0.98, 0]}>
            <mesh geometry={nodes.Plane003_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object036_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.7, 1.13, 0]}>
            <mesh geometry={nodes.Plane004_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.97, 0.82, 0.64]}>
            <mesh geometry={nodes.Plane025_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[0.61, 1.42, 0.3]}>
            <mesh geometry={nodes.Object016_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[0, 0.76, 0.67]}>
            <mesh geometry={nodes.Object046_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object039_1.geometry} material={materials.Glass_backlights_white__1} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object037_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object050_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[0, 0.76, 0.67]}>
            <mesh geometry={nodes.Object047_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[1.83, 0.99, 0]}>
            <mesh geometry={nodes.Object035_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object044_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object022_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[-1.67, 0.59, 0.38]}>
            <mesh geometry={nodes.Plane019_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object015_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.59, 0.78, 0.83]}>
            <mesh geometry={nodes.Object034_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object012_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[0.77, 1.31, 0]}>
            <mesh geometry={nodes.Object008_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object023_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object005_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object010_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object001_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object002_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[1.93, 0.52, 0]}>
            <mesh geometry={nodes.Object006_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[-0.26, 0.99, 0.71]}>
            <mesh geometry={nodes.Plane029_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.99, 0.45, 0.73]}>
            <mesh geometry={nodes.Cylinder010_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[0.71, 1.06, 0]}>
            <mesh geometry={nodes.Object194_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[-1.56, 0.47, 0.68]}>
            <mesh geometry={nodes.Object195_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[1.99, 0.45, 0.73]}>
            <mesh geometry={nodes.Object196_1.geometry} material={materials.front_lights_mat_2_vnytri_color} />
          </group>
          <group position={[-1.56, 0.47, 0.68]}>
            <mesh geometry={nodes.Cylinder009_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.66, 0.41, 0.16]}>
            <mesh geometry={nodes.Plane028_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[0, 0.28, 0.42]}>
            <mesh geometry={nodes.Tube001_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[0, 0.28, 0.42]}>
            <mesh geometry={nodes.Object186_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.5, 0.3, 0.74]}>
            <mesh geometry={nodes._3040_4_1S_M_902B_L_002_1.geometry} material={materials.Tire_mat_texture} />
          </group>
          <group position={[-1.04, 0.28, 0.79]}>
            <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.Koleso_mat_Base} />
          </group>
          <group position={[1.45, 0.28, 0.79]}>
            <mesh geometry={nodes.Cylinder006_1.geometry} material={materials.Koleso_mat_Base} />
          </group>
          <group position={[1.5, 0.3, 0.79]}>
            <mesh geometry={nodes.Object185_1.geometry} material={materials.Baked_Emblema} />
          </group>
          <group position={[-0.99, 0.3, 0.79]}>
            <mesh geometry={nodes.Object183_1.geometry} material={materials.Baked_Emblema} />
          </group>
          <group position={[-1.09, 0.3, 0.77]}>
            <mesh geometry={nodes.Box002_1.geometry} material={materials.Koleso_mat_support} />
          </group>
          <group position={[-0.99, 0.3, 0.74]}>
            <mesh geometry={nodes._3040_4_1S_M_902B_L_1_1.geometry} material={materials.Tire_mat_texture} />
          </group>
          <group position={[-0.98, 0.3, 0.76]}>
            <mesh geometry={nodes.Object031_1.geometry} material={materials.Koleso_tormoz_disk_mat} />
          </group>
          <group position={[1.4, 0.29, 0.76]}>
            <mesh geometry={nodes.Object180_1.geometry} material={materials.Koleso_mat_support} />
          </group>
          <group position={[1.5, 0.3, 0.77]}>
            <mesh geometry={nodes.Object182_1.geometry} material={materials.Koleso_tormoz_disk_mat} />
          </group>
          <group position={[-1.49, 0.43, 0]}>
            <mesh geometry={nodes.Object003_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object197_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.41, 1.41, 0]}>
            <mesh geometry={nodes.Cylinder007_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.65, 1.06, 0.23]}>
            <mesh geometry={nodes.Plane041_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[0, 0.85, 0.26]}>
            <mesh geometry={nodes.Plane042_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[0.22, 0.81, 0]}>
            <mesh geometry={nodes.Line007_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[0.78, 1.11, 0]}>
            <mesh geometry={nodes.Object218_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Object220_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[0, 0.85, 0.26]}>
            <mesh geometry={nodes.Object222_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object224_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object226_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object228_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object229_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[0.27, 0.22, 0]}>
            <mesh geometry={nodes.Object230_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object231_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object232_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object233_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object235_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object237_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[0.61, 1.42, 0.3]}>
            <mesh geometry={nodes.Object239_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.7, 1.13, 0]}>
            <mesh geometry={nodes.Object240_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-0.25, 0.25, -0.4]}>
            <mesh geometry={nodes.Plane044_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[-1, 0.93, 0.22]}>
            <mesh geometry={nodes.Plane045_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.46, 0.14, 0.55]}>
            <mesh geometry={nodes.Plane046_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[2, 0.85, 0.07]}>
            <mesh geometry={nodes.Cylinder015_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[2, 0.84, 0.07]}>
            <mesh geometry={nodes.Box005_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.85, 1.05, 0.29]}>
            <mesh geometry={nodes.Plane047_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-0.62, 0.93, -0.39]}>
            <mesh geometry={nodes.e1933_2K_M_166C_R_1_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.74, 0.48, 0]}>
            <mesh geometry={nodes.Line008_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.75, 0.48, 0]}>
            <mesh geometry={nodes.Object241_1.geometry} material={materials.Baked_Nomera} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object244_1.geometry} material={materials.Front_lights_Spec} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object245_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Plane034_1.geometry} material={materials.Baked_Torpeda_map} />
          </group>
          <group position={[0.44, 0.85, 0]}>
            <mesh geometry={nodes.Plane033_1.geometry} material={materials.baked_Tonel} />
          </group>
          <group position={[0.85, 0.88, 0.47]}>
            <mesh geometry={nodes.Box003_1.geometry} material={materials.baked_front_seat} />
          </group>
          <group position={[1.48, 1.03, 0.47]}>
            <mesh geometry={nodes.Cylinder014_1.geometry} material={materials.Baked_Back_sideniya} />
          </group>
          <group position={[1.22, 0.72, 0.57]}>
            <mesh geometry={nodes.Plane040_1.geometry} material={materials.baked_Back_Door} />
          </group>
          <group position={[0.17, 0.52, 0.66]}>
            <mesh geometry={nodes.Object198_1.geometry} material={materials.Baked_Dveri_obshivki} />
          </group>
          <group position={[0.78, 1.11, 0]}>
            <mesh geometry={nodes.Object247_1.geometry} material={materials.baked__Baked_Potolok} />
          </group>
          <group position={[0.17, 0.52, 0.66]}>
            <mesh geometry={nodes.Object248_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Object249_1.geometry} material={materials.Diffuse_Holes} />
          </group>
          <group position={[0.85, 0.88, 0.47]}>
            <mesh geometry={nodes.Object250_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[2, 0.67, -0.4]}>
            <mesh geometry={nodes.rubber_01_01_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[2, 0.67, -0.4]}>
            <mesh geometry={nodes.Object268_1.geometry} material={materials.M_Logo_Rot} />
          </group>
          <group position={[0, 0.64, 0.17]}>
            <mesh geometry={nodes.Box002__1__1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object246_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.98, 0.28, -0.05]}>
            <mesh geometry={nodes.Object269_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object270_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[1.66, 0, 0.26]}>
            <mesh geometry={nodes.Object246__1__1.geometry} material={materials.Kuzov_potolok} />
          </group>
          <group position={[1.66, 0, 0.26]}>
            <mesh geometry={nodes.Object247__1__1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[0.98, 1.4, 0]}>
            <mesh geometry={nodes.Object248__1__1.geometry} material={materials.PANARAMA} />
          </group>
          <group position={[1.33, 0.82, -0.82]}>
            <mesh geometry={nodes.Tube001__1__1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[8.74, 0.35, 0.5]}>
            <mesh geometry={nodes.Object265_1.geometry} material={materials['02___Default']} />
          </group>
          <group position={[8.74, 0.35, 0.5]}>
            <mesh geometry={nodes.Object266_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[1.64, 1.35, 0]}>
            <mesh geometry={nodes.Plane049_1.geometry} material={materials.Kuzov_potolok} />
          </group>
          <group position={[2.04, 0.43, 0]}>
            <mesh geometry={nodes.Object271_1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[-0.91, 0.29, 0]}>
            <mesh geometry={nodes._shell_146_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[2.01, 0.89, 0]}>
            <mesh geometry={nodes.Cylinder016_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[1.5, 0.3, 0.81]}>
            <mesh geometry={nodes.Object185__1__1.geometry} material={materials.Baked_Emblema} />
          </group>
          <group position={[-0.99, 0.3, 0.81]}>
            <mesh geometry={nodes.Object183__1__1.geometry} material={materials.Baked_Emblema} />
          </group>
          <group position={[0.78, 1.11, 0]}>
            <mesh geometry={nodes.LP_Potolok_1.geometry} material={materials.Baked_Potolok} />
          </group>
          <group position={[0.84, 1.37, -0.14]}>
            <mesh geometry={nodes.Plane001_1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[0.98, 1.37, 0]}>
            <mesh geometry={nodes.Object272_1.geometry} material={materials.PANARAMA} />
          </group>
          <group position={[-1.7, 0.6, 0.33]}>
            <mesh geometry={nodes.Object274_1.geometry} material={materials.M_Logo_Rot} />
          </group>
          <group position={[-1.69, 0.6, 0.32]}>
            <mesh geometry={nodes.Object275_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object276_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object277_1.geometry} material={materials.Kuzov_potolok} />
          </group>
          <group position={[-0.56, 0.78, -0.82]}>
            <mesh geometry={nodes.Object278_1.geometry} material={materials.M_Logo_Rot} />
          </group>
          <group position={[-0.56, 0.78, -0.82]}>
            <mesh geometry={nodes.Object279_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.56, 0.78, 0.82]}>
            <mesh geometry={nodes.Object280_1.geometry} material={materials.M_Logo_Rot} />
          </group>
          <group position={[-0.56, 0.78, 0.82]}>
            <mesh geometry={nodes.Object281_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object282_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.7, 0.65, 0.01]}>
            <mesh geometry={nodes.Object270__1__1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-0.42, 1, 0.34]}>
            <mesh geometry={nodes.Plane001__1__1.geometry} material={materials.Glass_front_lights} />
          </group>
          <group position={[-1.63, 0.74, 0]}>
            <mesh geometry={nodes.Cylinder017_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[0.87, -0.88, 0]}>
            <mesh geometry={nodes._shell_147_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object283_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[0.17, 0.52, 0.66]}>
            <mesh geometry={nodes.Object284_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Object285_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Object286_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Object287_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[0.44, 0.85, 0]}>
            <mesh geometry={nodes.Object288_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Object289_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[0.44, 0.85, 0]}>
            <mesh geometry={nodes.Object290_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.36, 1, -0.31]}>
            <mesh geometry={nodes.Object291_1.geometry} material={materials.Specular_Railing} />
          </group>
          <group position={[-0.28, 1.23, 0]}>
            <mesh geometry={nodes.Box002__2__1.geometry} material={materials.Salon_black} />
          </group>
          <group position={[-0.2, 1.2, 0]}>
            <mesh geometry={nodes.Plane001__2__1.geometry} material={materials.Mirrors_color} />
          </group>
          <group position={[0, 0.77, 0.6]}>
            <mesh geometry={nodes.Plane048_1.geometry} material={materials.Back_lights_emissive_color_01} />
          </group>
          <group position={[0, 0.77, 0.6]}>
            <mesh geometry={nodes.Object243_1.geometry} material={materials.Back_lights_emissive_color_01} />
          </group>
          <group position={[0.61, 1.42, 0.3]}>
            <mesh geometry={nodes.Object053_1.geometry} material={materials.Glass_Windows} />
          </group>
          <group position={[0.61, 1.42, 0.3]}>
            <mesh geometry={nodes.Object054_1.geometry} material={materials.Glass_Windows} />
          </group>
          <group position={[0.61, 1.42, 0.3]}>
            <mesh geometry={nodes.Object055_1.geometry} material={materials.Glass_Windows} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object056_1.geometry} material={materials.Glass_Windows} />
          </group>
          <group position={[2.03, 0.35, 0.5]}>
            <mesh geometry={nodes.Line012_1.geometry} material={materials.Back_Bamper} />
          </group>
          <group position={[1.67, 0.27, 0.47]}>
            <mesh geometry={nodes.Plane001__3__1.geometry} material={materials.Bottom_color} />
          </group>
          <group position={[1.98, 0.28, -0.05]}>
            <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0]}>
            <mesh geometry={nodes.Plane001__4__1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object250__1__1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[-1.49, 0.81, 0]}>
            <mesh geometry={nodes.Plane050_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.23, 0.95, 0.24]}>
            <mesh geometry={nodes.Object251_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object254_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Plane054_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object255_1.geometry} material={materials.Kuzov_Main_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object256_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object257_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object258_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object260_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object259_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.7, 0.28, 0.18]}>
            <mesh geometry={nodes.Plane055_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.72, 0.58, 0]}>
            <mesh geometry={nodes.Line011_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-1.67, 0.38, -0.55]}>
            <mesh geometry={nodes.Object262_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[2.1, 0.44, 0]}>
            <mesh geometry={nodes.Line013_1.geometry} material={materials.Kuzov_black_color} />
          </group>
          <group position={[-0.99, 0.3, -0.84]}>
            <mesh geometry={nodes.Object001__1__1.geometry} material={materials.Koles_mat_Spec} />
          </group>
          <group position={[-0.99, 0.3, 0]}>
            <mesh geometry={nodes.Plane001__5__1.geometry} material={materials.Koleso_mat_Base} />
          </group>
          <group position={[1.51, 0.3, -0.84]}>
            <mesh geometry={nodes.Object267_1.geometry} material={materials.Koles_mat_Spec} />
          </group>
          <group position={[1.51, 0.3, 0]}>
            <mesh geometry={nodes.Plane057_1.geometry} material={materials.Koleso_mat_Base} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/MiniCooper.gltf')
